// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CH_HashFiles/CHHashFileVPlain.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MFNHashFilePlainProtobuf_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MFNHashFilePlainProtobuf_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CHHashFileVPlain_2eproto() {
  protobuf_AddDesc_CHHashFileVPlain_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CHHashFileVPlain.proto");
  GOOGLE_CHECK(file != NULL);
  MFNHashFilePlainProtobuf_descriptor_ = file->message_type(0);
  static const int MFNHashFilePlainProtobuf_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MFNHashFilePlainProtobuf, hash_length_bytes_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MFNHashFilePlainProtobuf, hash_value_),
  };
  MFNHashFilePlainProtobuf_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MFNHashFilePlainProtobuf_descriptor_,
      MFNHashFilePlainProtobuf::default_instance_,
      MFNHashFilePlainProtobuf_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MFNHashFilePlainProtobuf, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MFNHashFilePlainProtobuf, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MFNHashFilePlainProtobuf));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CHHashFileVPlain_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MFNHashFilePlainProtobuf_descriptor_, &MFNHashFilePlainProtobuf::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CHHashFileVPlain_2eproto() {
  delete MFNHashFilePlainProtobuf::default_instance_;
  delete MFNHashFilePlainProtobuf_reflection_;
}

void protobuf_AddDesc_CHHashFileVPlain_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026CHHashFileVPlain.proto\"I\n\030MFNHashFileP"
    "lainProtobuf\022\031\n\021hash_length_bytes\030\001 \001(\r\022"
    "\022\n\nhash_value\030\002 \003(\014", 99);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CHHashFileVPlain.proto", &protobuf_RegisterTypes);
  MFNHashFilePlainProtobuf::default_instance_ = new MFNHashFilePlainProtobuf();
  MFNHashFilePlainProtobuf::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CHHashFileVPlain_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CHHashFileVPlain_2eproto {
  StaticDescriptorInitializer_CHHashFileVPlain_2eproto() {
    protobuf_AddDesc_CHHashFileVPlain_2eproto();
  }
} static_descriptor_initializer_CHHashFileVPlain_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int MFNHashFilePlainProtobuf::kHashLengthBytesFieldNumber;
const int MFNHashFilePlainProtobuf::kHashValueFieldNumber;
#endif  // !_MSC_VER

MFNHashFilePlainProtobuf::MFNHashFilePlainProtobuf()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MFNHashFilePlainProtobuf::InitAsDefaultInstance() {
}

MFNHashFilePlainProtobuf::MFNHashFilePlainProtobuf(const MFNHashFilePlainProtobuf& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MFNHashFilePlainProtobuf::SharedCtor() {
  _cached_size_ = 0;
  hash_length_bytes_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MFNHashFilePlainProtobuf::~MFNHashFilePlainProtobuf() {
  SharedDtor();
}

void MFNHashFilePlainProtobuf::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MFNHashFilePlainProtobuf::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MFNHashFilePlainProtobuf::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MFNHashFilePlainProtobuf_descriptor_;
}

const MFNHashFilePlainProtobuf& MFNHashFilePlainProtobuf::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CHHashFileVPlain_2eproto();  return *default_instance_;
}

MFNHashFilePlainProtobuf* MFNHashFilePlainProtobuf::default_instance_ = NULL;

MFNHashFilePlainProtobuf* MFNHashFilePlainProtobuf::New() const {
  return new MFNHashFilePlainProtobuf;
}

void MFNHashFilePlainProtobuf::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    hash_length_bytes_ = 0u;
  }
  hash_value_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MFNHashFilePlainProtobuf::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 hash_length_bytes = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &hash_length_bytes_)));
          set_has_hash_length_bytes();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_hash_value;
        break;
      }
      
      // repeated bytes hash_value = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_hash_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_hash_value()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_hash_value;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MFNHashFilePlainProtobuf::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional uint32 hash_length_bytes = 1;
  if (has_hash_length_bytes()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->hash_length_bytes(), output);
  }
  
  // repeated bytes hash_value = 2;
  for (int i = 0; i < this->hash_value_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->hash_value(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MFNHashFilePlainProtobuf::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional uint32 hash_length_bytes = 1;
  if (has_hash_length_bytes()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->hash_length_bytes(), target);
  }
  
  // repeated bytes hash_value = 2;
  for (int i = 0; i < this->hash_value_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(2, this->hash_value(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MFNHashFilePlainProtobuf::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 hash_length_bytes = 1;
    if (has_hash_length_bytes()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->hash_length_bytes());
    }
    
  }
  // repeated bytes hash_value = 2;
  total_size += 1 * this->hash_value_size();
  for (int i = 0; i < this->hash_value_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->hash_value(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MFNHashFilePlainProtobuf::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MFNHashFilePlainProtobuf* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MFNHashFilePlainProtobuf*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MFNHashFilePlainProtobuf::MergeFrom(const MFNHashFilePlainProtobuf& from) {
  GOOGLE_CHECK_NE(&from, this);
  hash_value_.MergeFrom(from.hash_value_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_hash_length_bytes()) {
      set_hash_length_bytes(from.hash_length_bytes());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MFNHashFilePlainProtobuf::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MFNHashFilePlainProtobuf::CopyFrom(const MFNHashFilePlainProtobuf& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MFNHashFilePlainProtobuf::IsInitialized() const {
  
  return true;
}

void MFNHashFilePlainProtobuf::Swap(MFNHashFilePlainProtobuf* other) {
  if (other != this) {
    std::swap(hash_length_bytes_, other->hash_length_bytes_);
    hash_value_.Swap(&other->hash_value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MFNHashFilePlainProtobuf::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MFNHashFilePlainProtobuf_descriptor_;
  metadata.reflection = MFNHashFilePlainProtobuf_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
